Guidelime.registerGuide(
[[
[GA Alliance]
[N1-9Human TUGs Leveling Guide]
[NX9-11 Dun Morogh, Loch Modan]
[D This guide was written by TUGs and is totally free, but if you want to support my work use: https://www.youtube.com/user/HydroxXTV]
This guide was written by TUGs and is totally free, but if you want to support my work use: https://www.youtube.com/user/HydroxXTV
Every Level you should grind 2-5 experience bars, this will make sure that this guide works properly!
Accept: [QA783]
TurnIn: [QT783]
Accept: [QA7]
Accept: [QA5261]
TurnIn: [QT5261]
Accept: [QA33]
Do: [QC33]
TurnIn: [QT33]
Accept: [QA18]
Accept: [QA1598][A Warlock]
Do: [QC1598][A Warlock]
Do: [QC18]
TurnIn: [QT18]
Accept: [QA3903]
Accept: [QA6]
TurnIn: [QT1598][A Warlock]
TurnIn: [QT3903]
Accept: [QA3904]
Do [QC3904- ][QC6]
Grind  this area till level [XP4+450 4+450]
Use your [H] Hearthstone.
TurnIn: [QT6]
TurnIn: [QT3904]
Accept: [QA3905]
Do: [QC7]
Sell your items at the vendor you need a couple silver.
TurnIn: [QT7]
Accept: [QA15]
Accept: [QA3100][A Warrior]
TurnIn: [QT3100][A Warrior]
Accept: [QA3101][A Paladin]
TurnIn: [QT3101][A Paladin]
Accept: [QA3105][A Warlock]
TurnIn: [QT3105][A Warlock]
Accept: [QA3104][A Mage]
TurnIn: [QT3104][A Mage]
[T] Get your Level 4 skills at your trainer.
TurnIn: [QT3905]
Do: [QC15]
TurnIn: [QT15]
Accept: [QA2158]
Accept: [QA60]
Set your [S] to Elwynn Forest at [G43.8,65.8Elwynn Forest]
TurnIn: [QT2158]
Accept: [QA62]
Accept: [QA47]
Kill all Boars(especially good on the fields you will go to) for 4x Chunk of Boar Meat
Accept: [QA106]
Well be crossing through the Kobold mine a couple of times now->Kill 2-3 Kobolds each time you do, to get some quest items already.
Accept: [QA85]
TurnIn: [QT106]
Accept: [QA111]
TurnIn: [QT111]
Accept: [QA107]
TurnIn: [QT85]
Accept: [QA86]
TurnIn: [QT86]
Accept: [QA84]
Grind  on the field nearby till level [XP6 6]
Accept: [QA88]
TurnIn: [QT84]
Accept: [QA87]
Do [QC62- ][QC47- ][QC60- ][QC87]
Die and rezz at Ghosthealer
TurnIn: [QT62]
Accept: [QA76]
Run to [G41.5,65.8Elwynn Forest][A Warrior,Paladin]
Buy: [CI2488,1 Gladius] [A Warrior]Buy a Gladius from Corina Steele[A Warrior]
Buy: [CI2493,1 Wooden Mallet] [A Paladin] Buy a Wooden Mallet from Corina Steele[A Paladin]
[T] Get your Level 6 skills at your trainer.[A Warrior,Paladin]
TurnIn: [QT47]
TurnIn: [QT107]
Accept: [QA112]
TurnIn: [QT60]
Accept: [QA61]
[T] Get your Level  skills at your trainer.[A Warlock,Mage,Priest,Rogue]
Do: [QC112]
Do: [QC76]
Die and rezz at Ghosthealer
TurnIn: [QT112]
Accept: [QA114]
Buy Missing 6Slot Bags so you got 4 bags.
TurnIn: [QT76]
Accept: [QA40]
TurnIn: [QT40]
Accept: [QA35]
Do(this is an optional quest!): [QC88]
TurnIn: [QT35]
Accept: [QA37]
Accept: [QA52]
TurnIn: [QT37]
Accept: [QA45]
Accept: [QA5545]
Do [QC5545- ][QC52]
TurnIn: [QT45]
Accept: [QA71]
TurnIn: [QT5545]
TurnIn: [QT52]
TurnIn: [QT71]
Accept: [QA39]
Use your [H] Hearthstone.
TurnIn: [QT114]
TurnIn: [QT88]
TurnIn: [QT87]
TurnIn: [QT39]
Accept: [QA1097]
[T] Get your Level 8 skills at your trainer.
TurnIn: [QT61]
TurnIn: [QT1097]
Accept: [QA353]
Take the Tram to Ironforge
Get the [P] flightpath at: [G55.5,47.8Ironforge]
]], "TUGs The Ultimate (Leveling) Guides")