Guidelime.registerGuide(
[[
[GA Alliance]
[N9-11 Dun Morogh, Loch Modan]
[NX11-18 Darkshore]
[D This guide was written by TUGs and is totally free, but if you want to support my work use: https://www.youtube.com/user/HydroxXTV]
This guide was written by TUGs and is totally free, but if you want to support my work use: https://www.youtube.com/user/HydroxXTV
Every Level you should grind 2-5 experience bars, this will make sure that this guide works properly!
Accept: [QA314][O]
Do(This is an OPTIONAL ELITE quest, do it if you can or find a group, if you cant->skip it): [QC314]
TurnIn: [QT314][O]
Accept: [QA433]
Accept: [QA432]
Do [QC433- ][QC432]
Farm till youre level[XP9+4500]
TurnIn: [QT433]
TurnIn: [QT432]
Accept: [QA419]
TurnIn: [QT419]
Accept: [QA417]
Do: [QC417]
TurnIn: [QT417]
Accept: [QA224]
Accept: [QA267]
Get the [P] flightpath at: [G33.9,51Loch Modan][A Hunter]
Fly to [F Ironforge][A Hunter]
Accept: [QA6064][A Hunter]
Do: [QC6064][A Hunter]
TurnIn: [QT6064][A Hunter]
Accept: [QA6084][A Hunter]
Do: [QC6084][A Hunter]
TurnIn: [QT6084][A Hunter]
Accept: [QA6085][A Hunter]
Do: [QC6085][A Hunter]
TurnIn: [QT6085][A Hunter]
Accept: [QA6086][A Hunter]
[A Hunter]Tame a pet you like.I highly recommend a boar. Charge that deals more dmg and roots and as its a charge it can attack earlier->More aggro!
TurnIn: [QT6086][A Hunter]
[A Hunter]Feed your pet and [T] Train your own and your pets skills.
Fly to [F Loch Modan][A Hunter]
Do: [QC224]
Do: [QC267]
TurnIn: [QT224]
Accept: [QA237]
TurnIn: [QT267]
Get the [P] flightpath at: [G33.9,51Loch Modan]
Set your [S] to Loch Modan at [G35.4,48.4Loch Modan]
Accept: [QA6387][A Dwarf, Gnome]
Accept: [QA1339]
TurnIn: [QT353][A Human]
TurnIn: [QT1339]
Accept: [QA307]
Do: [QC307]
Buy: [CI4778,1 Heavy Spiked Mace] from [G42.8,10Loch Modan]Nillen Andemar - Its a limited supply weapon,so it might not be available[A Warrior,Paladin]
TurnIn: [QT307]
Use your [H] Hearthstone.
TurnIn: [QT6387][A Dwarf, Gnome]
Accept: [QA6391][A Dwarf, Gnome]
Fly to [F Ironforge]
TurnIn: [QT6391][A Dwarf, Gnome]
Accept: [QA6388][A Dwarf, Gnome]
TurnIn: [QT291][A Dwarf, Gnome]
[T] Get your Level 10 skills at your trainer.
Accept: [QA1715][A Warlock]
Set your [S] to Ironforge at [G18.6,51.6Ironforge]
Run to [G30.9,36.5Dun Morogh][A Human]
Run to [G31.1,31.2Dun Morogh][A Human]
Run to [G32.8,29.1Dun Morogh][A Human]
Run to [G32.9, 27.5Dun Morogh][A Human]
[A Human] There is a hill infront of you, that gets you into "The Great Sea"(Above your minimap). Go ontop of that.
[A Human] Jump to your death towards north, Rezz up at the Spirit Healer.
TurnIn: [QT6388][A Dwarf, Gnome]
Get the [P] flightpath at: [G9.6,59.6Wetlands][A Human]
Fly to [F Stormwind]
Take the ship to Darkshore
]], "TUGs The Ultimate (Leveling) Guides")